#!/usr/bin/env bash
sudo apt install curl gnupg2 ca-certificates lsb-release ubuntu-keyring -y
echo "deb [signed-by=/usr/share/keyrings/nginx-archive-keyring.gpg] \
http://nginx.org/packages/ubuntu $(lsb_release -cs) nginx" \
    | sudo tee /etc/apt/sources.list.d/nginx.list
sudo apt install nginx -y
nginx -s reload
