#!/usr/bin/env bash
#simple script to modify the http header of a nginx server
sudo apt update
sudo apt install nginx -y
sed -i "/^server {/a\ \ \ \ \ \ \ \ add_header X-Served-By $(cat /etc/hostname);" /etc/nginx/sites-enabled/default
