#!/usr/bin/env bash
#simple script to install HA-proxy
sudo apt update
sudo apt-get install --no-install-recommends software-properties-common -y
sudo add-apt-repository ppa:vbernat/haproxy-2.8 -y
sudo apt-get install haproxy=2.8.\* -y
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
cat << EOF | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null
backend webservers
	balance roundrobin
	server web-01 35.153.231.171:80 check
	server web-02 54.157.168.18:80 check
EOF
sudo service haproxy start
