#!/usr/bin/env bash
#
i=1
echo "$$" > /var/run/myscript.pid
function CLEANUP
{
	rm '/var/run/myscript.pid'
	exit
}
trap 'echo "Y U no love me?!"; CLEANUP' SIGINT
trap 'echo "Y U no love me?!"; CLEANUP' SIGQUIT
trap 'echo "I hate the kill command"; CLEANUP' SIGTERM
while [ $i -ge 1 ]; do
	echo "To infinity and beyond"
done
