#!/usr/bin/env bash
#simple script to print words
i=1
while [ "$i" -lt 10 ]; do
	if [ "$i" -eq 4 ]
	then
		echo "bad luck"
	elif [ "$i" -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++))
done
