#!/usr/bin/env bash
#displays the time for 12hours and 59min
hour=0
min=0
while [ "$hour" -le 12 ]; do
	echo "Hour: $hour"
	while [ "$min" -le 59 ]; do
		echo "$min"
		((min++))
	done
	((min=0))
	((hour++))
done
	
