#!/usr/bin/env bash
#update new ips for localhost and facebook
cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1\s*localhost/127.0.0.2	localhost/' ~/hosts.new
cp ~/hosts.new /etc/hosts
echo "8.8.8.8	facebook.com" >> /etc/hosts
